# Generated by Django 6.0 on 2026-02-01 05:47
from django.db import migrations, models
import django.db.models.deletion


def set_owner_to_raymond(apps, schema_editor):
    """Assign all existing records to Raymond (ID=2)"""
    User = apps.get_model('auth', 'User')
    Client = apps.get_model('core', 'Client')
    Worker = apps.get_model('core', 'Worker')
    Task = apps.get_model('core', 'Task')
    
    # Get Raymond - use 'Raymond' with capital R since that's your actual username
    raymond, created = User.objects.get_or_create(
        id=2,
        defaults={
            'username': 'Raymond',  # Capital R as you specified
            'email': '',
            'is_staff': True,
            'is_superuser': True
        }
    )
    
    if created:
        raymond.set_password('Admin')
        raymond.save()
        print(f"Created Raymond user with ID: {raymond.id}")
    else:
        print(f"Found existing Raymond: ID={raymond.id}, Username='{raymond.username}'")
    
    # Update all null owners
    client_count = Client.objects.filter(owner__isnull=True).update(owner=raymond)
    worker_count = Worker.objects.filter(owner__isnull=True).update(owner=raymond)
    task_count = Task.objects.filter(owner__isnull=True).update(owner=raymond)
    
    print(f"Updated {client_count} clients, {worker_count} workers, {task_count} tasks to Raymond")

def reverse_set_owner(apps, schema_editor):
    """Reverse: Set owners back to null"""
    Client = apps.get_model('core', 'Client')
    Worker = apps.get_model('core', 'Worker')
    Task = apps.get_model('core', 'Task')
    
    Client.objects.all().update(owner=None)
    Worker.objects.all().update(owner=None)
    Task.objects.all().update(owner=None)
    print("Reversed: Set all owners to null")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_owner_task_owner_worker_owner'),
    ]

    operations = [
        # 1. First run the data migration
        migrations.RunPython(set_owner_to_raymond, reverse_set_owner),
        
        # 2. Then alter the fields to be non-nullable
        migrations.AlterField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='clients',
                to='auth.user'
            ),
        ),
        migrations.AlterField(
            model_name='worker',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='workers',
                to='auth.user'
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tasks',
                to='auth.user'
            ),
        ),
    ]